/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        wordmark: ['var(--font-wordmark)', 'var(--font-sans)', 'sans-serif'],
      },
      colors: {
        border: '#212A35',
        background: '#0A0E13',
        foreground: '#E7ECF2',
        primary: {
          DEFAULT: '#1E63FF',
          foreground: '#F2F5FA',
        },
        accent: '#212A35',
        brand: {
          ink: '#0A0F1C',
          blue: '#1E63FF',
          cyan: '#00D4FF',
          purple: '#7B61FF',
          green: '#00C896',
          gray: '#64748B',
          paper: '#F2F5FA',
        },
        teal: {
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#00D4AA',
          600: '#00A884',
          700: '#007A62',
        },
        // Keep some from original for compatibility
        'primary-fixed-dim': '#c4c5dd',
        'on-surface-variant': '#c7c5cd',
        'secondary-fixed-dim': '#00daf8',
        'tertiary-fixed-dim': '#d6c5a1',
        'inverse-primary': '#5b5d72',
        'on-background': '#d4e4fa',
        'surface-container-highest': '#273647',
        'surface-container': '#122131',
        'surface-container-lowest': '#010f1f',
        'tertiary-container': '#251c05',
        'on-tertiary-container': '#928464',
        'on-primary': '#2d2f42',
        'on-primary-fixed': '#181a2c',
        'on-surface': '#d4e4fa',
        'on-error-container': '#ffdad6',
        outline: '#919097',
        surfaceTint: '#c4c5dd',
        'primary-container': '#1a1c2e',
        surfaceBright: '#2c3a4c',
        'on-tertiary-fixed': '#231a04',
        surfaceDim: '#051424',
        secondaryFixed: '#a5eeff',
        onSecondary: '#00363f',
        onSecondaryContainer: '#005f6d',
        surfaceVariant: '#273647',
        inverseOnSurface: '#233143',
        onError: '#690005',
        surfaceContainerHigh: '#1c2b3c',
        primaryFixed: '#e0e0fa',
        'on-primary-fixed-variant': '#444559',
        onPrimaryContainer: '#82849a',
        onSecondaryFixedVariant: '#004e5a',
        outlineVariant: '#46464c',
        surfaceContainerLow: '#0d1c2d',
        onTertiary: '#3a2f16',
        errorContainer: '#93000a',
        secondary: '#b9f1ff',
        // Additional colors used in dashboard
        red: '#E5555A',
        blue: '#5B9BD9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1440px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        unit: '8px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease forwards',
        'slide-up': 'slide-up 0.4s ease forwards',
        'pulse-glow': 'pulse-glow 2s infinite',
        // Keep existing if any
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(0, 212, 170, 0.4)' },
          '50%': { boxShadow: '0 0 0 6px rgba(0, 212, 170, 0)' },
        },
        // Keep existing if any
      },
    },
  },
  plugins: [],
};
