'use client';

import { FileText } from 'lucide-react';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/page-header';
import { useAppStore } from '@/store/app-store';

export default function HistoryPage() {
  const { reports } = useAppStore();

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <PageHeader
        title="Report History"
        description="Portfolio reports generated by the Builder — stored for this session."
      />

      {reports.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#212A35] bg-[#122131]/30 py-16 text-center">
          <FileText className="mb-4 h-10 w-10 text-[#8B95A5]" />
          <h3 className="text-lg font-semibold text-white">No reports yet</h3>
          <p className="mt-2 max-w-sm text-sm text-[#8B95A5]">
            Run the Portfolio Builder to generate your first AI portfolio analysis.
          </p>
          <Link
            href="/dashboard/builder"
            className="mt-6 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-[#F2F5FA] hover:bg-[#3D77FF] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0A0E13]"
          >
            Open Builder
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((report: { id?: string; createdAt?: string; email?: string }, i: number) => (
            <div
              key={report.id || i}
              className="flex items-center justify-between rounded-xl border border-[#212A35] bg-[#122131]/50 p-4"
            >
              <div className="flex items-center gap-3">
                <FileText className="h-5 w-5 text-primary" />
                <div>
                  <p className="font-medium text-white">Portfolio Report</p>
                  <p className="text-xs text-[#8B95A5]">
                    {report.createdAt || 'Recently'} · Sent to {report.email || 'your inbox'}
                  </p>
                </div>
              </div>
              <button className="rounded text-sm font-medium text-primary hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0A0E13]">
                View
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
